title: BAG Wiki
description: A wiki for BAG to share IT/python FAQs and tips. 
theme: just-the-docs

url: https://bjsilver.github.io/bag_wiki/

aux_links:
  Github Repository: https://github.com/bjsilver/bag_wiki

logo: "/assets/cute_BAG_pic.jpeg"
favicon_ico: "/assets/cute_BAG_pic.jpeg"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
